name: Deploy Flask App

on:
  push:
    branches:
      - main  # Deploy on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t book-summary-app .

      - name: Run Flask app in Docker
        run: |
          docker run -d -p 5000:5000 book-summary-app
